"""Constants used in the project."""

from configuration.utils.typing_custom import Sex

FIRST_TAB_NAME: str = "About"
SECOND_TAB_NAME: str = "2D agent"
THIRD_TAB_NAME: str = "3D pedestrian"
FOURTH_TAB_NAME: str = "Anthropometry"
FIFTH_TAB_NAME: str = "Crowd"
SIXTH_TAB_NAME: str = "Custom crowd"

# 2D / 3D shapes tab
DEFAULT_PEDESTRIAN_HEIGHT: float = 170.0  # cm
DEFAULT_HEIGHT_MIN: float = 100.0  # in cm
DEFAULT_HEIGHT_MAX: float = 230.0  # in cm

DEFAULT_PEDESTRIAN_WEIGHT: float = 70.0  # kg
DEFAULT_BIKE_WEIGHT: float = 30.0  # kg

MAX_TRANSLATION_X: float = 500.0  # cm
MAX_TRANSLATION_Y: float = 500.0  # cm

DEFAULT_SEX: Sex = "male"

# Crowd tab
DEFAULT_BOUNDARY_X: float = 200.0  # cm
DEFAULT_BOUNDARY_X_MIN: float = 50.0  # cm
DEFAULT_BOUNDARY_X_MAX: float = 2000.0  # cm
DEFAULT_BOUNDARY_Y: float = 200.0  # cm
DEFAULT_BOUNDARY_Y_MIN: float = 50.0  # cm
DEFAULT_BOUNDARY_Y_MAX: float = 2000.0  # cm

DEFAULT_AGENT_NUMBER: int = 4
DEFAULT_AGENT_NUMBER_MIN: int = 1
DEFAULT_AGENT_NUMBER_MAX: int = 300

MAX_MOVE_X: float = 50.0  # cm
MAX_MOVE_Y: float = 50.0  # cm
MAX_ROTATION_ANGLE: float = 30.0  # degrees

DEFAULT_REPULSION_LENGTH_MIN: float = 4.0
DEFAULT_REPULSION_LENGTH_MAX: float = 70.0

DEFAULT_WALL_INTERACTION: float = False

# Crowd Statistics
DEFAULT_MALE_PROPORTION: float = 0.5
DEFAULT_PEDESTRIAN_PROPORTION: float = 1.0
DEFAULT_BIKE_PROPORTION: float = 1.0 - DEFAULT_PEDESTRIAN_PROPORTION

DEFAULT_PEDESTRIAN_WEIGHT_MEAN: float = 70.0  # kg
DEFAULT_PEDESTRIAN_WEIGHT_MIN: float = 10.0  # kg
DEFAULT_PEDESTRIAN_WEIGHT_MAX: float = 100.0  # kg
DEFAULT_PEDESTRIAN_WEIGHT_STD_DEV: float = 5.0  # kg

DEFAULT_BIKE_WEIGHT_MEAN: float = 30  # kg
DEFAULT_BIKE_WEIGHT_MIN: float = 10.0  # kg
DEFAULT_BIKE_WEIGHT_MAX: float = 100.0  # kg
DEFAULT_BIKE_WEIGHT_STD_DEV: float = 5.0  # kg

DEFAULT_BIDELTOID_BREADTH_MIN: float = 30.0  # in cm
DEFAULT_BIDELTOID_BREADTH_MAX: float = 90.0  # in cm
DEFAULT_CHEST_DEPTH_MIN: float = 15.0  # in cm
DEFAULT_CHEST_DEPTH_MAX: float = 50.0  # in cm

DEFAULT_MALE_BIDELTOID_BREADTH_MEAN: float = 51.0  # cm
DEFAULT_MALE_BIDELTOID_BREADTH_STD_DEV: float = 2.0  # cm
DEFAULT_MALE_CHEST_DEPTH_MEAN: float = 26.0  # cm
DEFAULT_MALE_CHEST_DEPTH_STD_DEV: float = 2.0  # cm

DEFAULT_FEMALE_BIDELTOID_BREADTH_MEAN: float = 45.0  # cm
DEFAULT_FEMALE_BIDELTOID_BREADTH_STD_DEV: float = 1.5  # cm
DEFAULT_FEMALE_CHEST_DEPTH_MEAN: float = 24.0  # cm
DEFAULT_FEMALE_CHEST_DEPTH_STD_DEV: float = 1.5  # cm

DEFAULT_WHEEL_WIDTH_MEAN: float = 16.0  # cm
DEFAULT_WHEEL_WIDTH_STD_DEV: float = 2.0  # cm
DEFAULT_WHEEL_WIDTH_MIN: float = 5.0  # cm
DEFAULT_WHEEL_WIDTH_MAX: float = 30.0  # cm
DEFAULT_TOTAL_LENGTH_MEAN: float = 142.0
DEFAULT_TOTAL_LENGTH_STD_DEV: float = 5.0
DEFAULT_TOTAL_LENGTH_MIN: float = 100.0  # cm
DEFAULT_TOTAL_LENGTH_MAX: float = 200.0  # cm
DEFAULT_HANDLEBAR_LENGTH_MEAN: float = 60.0
DEFAULT_HANDLEBAR_LENGTH_STD_DEV: float = 5.0
DEFAULT_HANDLEBAR_LENGTH_MIN: float = 30.0  # cm
DEFAULT_HANDLEBAR_LENGTH_MAX: float = 90.0  # cm
DEFAULT_TOP_TUBE_LENGTH_MEAN: float = 61.0
DEFAULT_TOP_TUBE_LENGTH_STD_DEV: float = 5.0
DEFAULT_TOP_TUBE_LENGTH_MIN: float = 40.0  # cm
DEFAULT_TOP_TUBE_LENGTH_MAX: float = 90.0  # cm
